version: '3.9'
services:
  #  app:
  #    container_name: app-springboot-postgresql
  #    image: app-springboot-postgresql
  #    build: ./
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Password1*
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tasks
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: dbpostgresql
      DB_PORT: 5432
      DB_DATABASE: keycloack
      DB_USER: postgres
      DB_PASSWORD: Password1*
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - dbpostgresql